### ISSUE TITLE
You can make the code for the priest like this, or it is manually

### ISSUE THREAD

**Issue by cisasmendi** [SphaeroX/Klipper-Pressure-advance-Macro#1]
You can make the code for the priest like this, or it is manually

; Call the Pressure Advance macro
CALCULATE_PA MATERIAL=PLA BOWDEN_LENGTH=20 LAYER_HEIGHT=[layer_height] NOZZLE_SIZE=[nozzle_diameter] PRINT_SPEED=[perimeter_speed]

**Comment by SphaeroX** [comment]
Code was updated
