### ISSUE TITLE
Calculating material constants

### ISSUE THREAD

**Issue by joshuahiggins** [SphaeroX/Klipper-Pressure-advance-Macro#2]
First off, nice work with this script. It's been matching up well with manual calculations for me.

How are the material constants determined? I'm looking to either replace the material input with a numeric one, or add additional materials to my constants. Since so many manufacturers are putting additives in these days, I would prefer a bit more flexibility.

Any help would be appreciated.

**Comment by SphaeroX** [comment]
Hey, I took comparative values and fed them into ChatGPT to establish these constants. Nothing special but it works fine for me.

**Comment by joshuahiggins** [comment]
Ahhh gotcha. I've gotta assume it can be calculated based on thermal expansion coefficient, temp, and some of the other values already incorporated. But that is above my knowledge.
